language: node_js
node_js:
  - 12

before_install:
  - yarn add codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js

branches:
  only:
    - master
